# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: registry.gitlab.com/coderrect/openrace

default:
  interruptible: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  

.MR: &on_merge_request
  rules:
    - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      changes:
        - src/**/*
        - tests/**/*
    - if: $CI_COMMIT_TAG
    - if: $CI_DEFAULT_BRANCH
      

build:
  stage: build
  #<<: *on_merge_request
  script:
    - mkdir -p build && cd build
    - conan install ..
    - cmake -DLLVM_DIR=/llvm-project/build/lib/cmake/llvm/ ..
    - cmake --build .
  artifacts:
    expire_in: 1 hour
    paths:
      - build/
  # Cannot have cache and artifact of same directory
  #cache:
  #  paths:
  #    - build/

test:
  stage: test
  #<<: *on_merge_request
  script:
    - cd build
    - ctest
  artifacts:
    expire_in: 7 days
    paths:
      - build/testresults/
    reports:
      junit:
        - build/testresults/*.xml
