version: 2

jobs:
  build:
    docker: 
      - image: coderrect/openrace-env
    steps:
      - checkout
      - run: mkdir build && cd build
      - run: cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=$BUILD_TYPE -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
      - run: cmake -- build . --parallel
    persist_to_workspace:
      root: .
      paths: 
       - bin
       - DartConfiguration.tcl
  test:
    docker: 
     - image: coderrect/openrace-en
    steps:
     - attach_workspace:
        at: .
     - run: ctest --parallel $(nproc)
    


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
        - requires:
          - build
        