version: 2

jobs:
  build:
    docker: 
      - image: coderrect/openrace-env
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            pwd
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build . --parallel $(nproc)
            ctest --parallel $(nproc)
      - store_artifacts:
          path: build/testresults
      - store_test_results:
          path: build/testresults


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
        