version: 2

jobs:
  build:
    docker: 
      - image: coderrect/openrace-env
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            pwd
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
            cmake --build . --parallel 2
            ctest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
        