version: 2

jobs:
  build:
    working_directory:
    docker: 
      - image: coderrect/openrace-env
    steps:
      - checkout
      - run:
        name: "sample"
        command: | 
          cd OpenRace
          pwd
          mkdir build && cd build
          pwd
          cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_BUILD_TYPE=$BUILD_TYPE -DLLVM_DIR=/usr/local/lib/cmake/llvm/ ..
          cmake -- build . --parallel
    persist_to_workspace:
      root: .
      paths: 
       - bin
       - DartConfiguration.tcl
  test:
    docker: 
     - image: coderrect/openrace-env
    steps:
     - attach_workspace:
        at: .
     - run: ctest --parallel $(nproc)
    
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
        